# -*- coding: utf-8 -*-
"""migration_sabotage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1olarExzBiYBB3Vx1jkx9BC8Vuf2CT0zP

# Phase 1: Data Preparation & The Migration Sabotage

### Business Task:
Before we can audit a failed database migration, we need to establish the "ground truth" of the legacy system. The raw sales data is currently split across three separate yearly files (2020, 2021, 2022).

### Action:
Load the three yearly CSV files, concatenate them into a single `Master_Legacy_Sales` dataset, and verify the row counts to ensure no data is lost during the merge.
"""

import pandas as pd
import numpy as np

sales_2020 = pd.read_csv("/content/Company Sales Data 2020.csv")
print(f"Total rows loaded for 2020: {len(sales_2020)}")

sales_2021 = pd.read_csv("/content/Company Sales Data 2021.csv")
print(f"Total rows loaded for 2021: {len(sales_2021)}")

sales_2022 = pd.read_csv("/content/Company Sales Data 2022.csv")
print(f"Total rows loaded for 2022: {len(sales_2022)}")

Master_sales = pd.concat([sales_2020, sales_2021, sales_2022], ignore_index= True)
print(f"Total rows loaded for Master_sales: {len(Master_sales)}")

# The Audit Check
expected_total = sum([len(sales_2020), len(sales_2021), len(sales_2022)])
actual_total = len(Master_sales)

print(f"\n---Merge Audit---")
print(f"Expected Total Rows(Sum of 3 years): {expected_total}")
print(f"Actual Total Rows(Master_sales): {actual_total}")
print(f"Variance(Data Loss): {expected_total - actual_total}")

if expected_total == actual_total:
  print("✅Status: Merge Successful. Ground Truth Established")
else:
  print("❌Status: Merge Unsuccessful. Do not Proceed")

"""# Phase 2: Simulating the Migration Failure (The Sabotage)

### Business Task:
To build a reconciliation engine, we need broken data to audit. We will simulate a failed data migration from the Legacy CRM to the new Cloud Data Warehouse.

### Action:
We will create a `Cloud_System` copy of our master data and inject two specific real-world errors:
1. **Completeness Error (API Timeout):** Randomly drop exactly 60 records.
2. **Value Integrity Error (Float Mutation):** Randomly corrupt the `OrderQuantity` on 40 records to simulate data type conversion errors during the ETL process.
"""

# Create a copy - this will become our "Cloud" system with errors
df_legacy = Master_sales
df_cloud = df_legacy.copy()

print(f"\n Cloud Copy created: {len(df_cloud)} rows.")

# Error Type 1: Completeness Error (API Timeout)
# Real world: ETL jobs time out, network drops, batches fail silently
np.random.seed(42)
rows_to_delete = np.random.choice(df_cloud.index, size=60, replace=False)
df_cloud = df_cloud.drop(rows_to_delete)

print(f"\nCloud after 'mitigation error': {len(df_cloud)} rows.")
print(f"Missing rows: {len(df_legacy) - len(df_cloud)}")

# Error Type 2: Value Integrity Error (Data Type Conversion)
# Real world: API sync glitches, off-by-one errors, decimal rounding issues
np.random.seed(123)
rows_to_corrupt = np.random.choice(df_cloud.index, size=40, replace=False)

# Generate 40 random small changes: -2, -1, +1, or +2
deltas = np.random.choice([-2, -1, 1, 2], size=40)

# Apply changes instantly (vectorized - no for loop)
new_values = df_cloud.loc[rows_to_corrupt, 'OrderQuantity'] + deltas

# Ensure no quantity drops below 1 (can't sell 0 bikes)
# np.maximum compares each value to 1 and keeps the higher one
df_cloud.loc[rows_to_corrupt, 'OrderQuantity'] = np.maximum(new_values, 1)

print(f"\nCorrupted {len(rows_to_corrupt)} quantity values")
print(f"Sample changes: +1, -2, +1, -1 (realistic data entry errors)")

# Save the two systems
import os
os.makedirs('data_corrupted', exist_ok=True)

df_legacy.to_csv('data_corrupted/legacy_system.csv', index=False)
df_cloud.to_csv('data_corrupted/cloud_system.csv', index=False)

print("\nFiles saved:")
print("1. data_corrupted/legacy_system.csv (perfect original)")
print("2. data_corrupted/cloud_system.csv (broken migration)")